//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.19 at 12:10:22 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.springwebservices.org/product/schema/beans")
package org.springwebservices.product.schema.beans;
